### ISSUE TITLE
Let rust and node handshake

### ISSUE THREAD

**Issue by Frando** [Frando/hypercore-protocol-rs#1]
The handshake does not work at the moment. See [this issue in datrs/hypercore](https://github.com/datrs/hypercore/issues/92) for a high-level overview.

This issue is only concerned with the handshake. I managed to track down where exactly the handshake fails:

It's always the **client** (initiator) that crashes. And both in Rust and in Node it happens at the same place. It happens when receiving the **S** token and then calling into the [SymetricState](http://noiseprotocol.org/noise.html#the-symmetricstate-object) and its `DecryptAndHash` function. There, the cipher's `DecryptWithAd` function is called, and this decryption fails.

* In rust, the error occurs [here in symmetricstate.rs](https://github.com/mcginty/snow/blob/master/src/symmetricstate.rs#L96) when called from [handshakestate.rs when receiving the S token](https://github.com/mcginty/snow/blob/master/src/handshakestate.rs#L381)
* In node, the error occurs [here in symmetric-state.js](https://github.com/emilbayes/noise-protocol/blob/master/symmetric-state.js#L122) when called from [handshake-state.js when receiving the S token](https://github.com/emilbayes/noise-protocol/blob/master/handshake-state.js#L389)

So - either the input parameters to the decrypt function are different, or the XChaCha20 impls differ.

**Comment by Frando** [comment]
The [README of noise-protocol](https://github.com/emilbayes/noise-protocol#deviations-from-the-noise-specification) states the following:

> ## Deviations from the Noise specification
>
> * Uses `libsodium`s `crypto_kx_*` API which hashes the shared secret with the
>  client and server public key; `BLAKE2b-512(shared || client_pk || server_pk)`
>* Uses `crypto_aead_xchacha20poly1305_ietf_*` for symmetric cryptography with
>  nonces `128-bit zero || 64-bit counter`, meaning the protocol name is `Noise_*_25519_XChaChaPoly_BLAKE2b`, with `*` being the handshake pattern

**Comment by Frando** [comment]
I hackily replaced the x25519 DH calculation in snow with crypto_kx_* from sodiumoxide and again, it works between rust and rust but not rust and node/noise-protocol. Hm.

**Comment by bltavares** [comment]
I'm trying the following, yet I'm not sure what should be the values for Key to initiate the XSalsa20 stream:

https://github.com/Frando/hypercore-protocol-rust-experiments/compare/master...bltavares:cipher

It compiles, but I didn't even try to run as the keys are dummy values so far.

**Comment by Frando** [comment]
I managed to get this to work :sweat_smile: 

still not with the released versions, but it works!

**Comment by Frando** [comment]
This was fixed quite a while ago
